name: ETL-Automatico-Salesforce

on:
  schedule:
  - cron: "0 13,17,21,23 * * 1-5"
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
      
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
    

  # ============================================================
  # 🔹 ASISTENCIA EXTRACURRICULAR
  # ============================================================
    
    - name: Ejecutar Extracurriculares 2025 - Descargar
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python "etl/procesos/2025/2. asistencia_extracurricular/01_descarga.py"
    
    - name: Ejecutar Extracurriculares 2025 - Transformación
      run: python "etl/procesos/2025/2. asistencia_extracurricular/02_transformacion.py"
    
    - name: Ejecutar Consolidación - Extracurriculares
      run: python "etl/procesos/consolidacion/2_asistencia_extracurricular.py"
    
    - name: Ejecutar carga a Salesforce - Extracurriculares
      run: python "etl/procesos/carga/02_asistencia_extracurricular.py"

        
# ============================================================
# 🔹 Artefactos
# ============================================================
         
    - name: Subir todos los artefactos
      uses: actions/upload-artifact@v4
      with:
        name: data-artifacts
        path: data/**
        retention-days: 1

